### ISSUE TITLE
Don't use retrolambda in library module

### ISSUE THREAD

**Issue by johnkil** [patloew/RxLocation#19]
I noticed such a thing, if the project uses Jack & Jill, you can get the following exception:

```
FATAL EXCEPTION: RxCachedThreadScheduler-1
io.reactivex.exceptions.UndeliverableException: java.lang.NoSuchMethodError: No virtual method com_patloew_rxlocation_Geocoding$$Lambda$2_lambda$fromLocation$2(Ljava/util/Locale;DDI)Ljava/util/List; in class Lcom/patloew/rxlocation/Geocoding; or its super classes (declaration of 'com.patloew.rxlocation.Geocoding' appears in /data/app/com.luckywhen.android-1/base.apk)
    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:62)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NoSuchMethodError: No virtual method com_patloew_rxlocation_Geocoding$$Lambda$2_lambda$fromLocation$2(Ljava/util/Locale;DDI)Ljava/util/List; in class Lcom/patloew/rxlocation/Geocoding; or its super classes (declaration of 'com.patloew.rxlocation.Geocoding' appears in /data/app/com.luckywhen.android-1/base.apk)
    at com.patloew.rxlocation.Geocoding$$Lambda$2.call(Unknown Source)
    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
    at io.reactivex.Single.subscribe(Single.java:2692)
    at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
    at io.reactivex.Scheduler$1.run(Scheduler.java:138)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
```

**Comment by patloew** [comment]
Strange. As far as I know Jill should not have a problem with Retrolambda, because for libraries it consumes Java class files in jars/aars and Retrolambda produces valid class files. I'll look into it, but I'm not a fan of removing Retrolambda, since the code is much cleaner this way.

**Comment by johnkil** [comment]
Maybe if you use the latest version of retrolambda this will solve the problem?

**Comment by johnkil** [comment]
https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html
