### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException 

### ISSUE THREAD

**Issue by z-sergei** [patloew/RxLocation#48]
Hello! Found a strange crash in Fabric that i can't reproduce by myself:
```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: com.patloew.rxlocation.StatusException: Status{statusCode=RESOLUTION_REQUIRED, resolution=PendingIntent{1f7965c5: android.os.BinderProxy@1f108b1a}}
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:97)
       at com.patloew.rxlocation.SingleResultCallBack.onResult(SingleResultCallBack.java:48)
       at com.google.android.gms.internal.zzaaf$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaaf$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5389)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by com.patloew.rxlocation.StatusException: Status{statusCode=RESOLUTION_REQUIRED, resolution=PendingIntent{1f7965c5: android.os.BinderProxy@1f108b1a}}
       at com.patloew.rxlocation.SingleResultCallBack.onResult(SingleResultCallBack.java:48)
       at com.google.android.gms.internal.zzaaf$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaaf$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5389)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

My code:
```
//init location in App
rxLocation = RxLocation(context)

// usage
rxLocation.settings()
   .check(locationRequest)
   .map { true }
   .onErrorReturn { false }
   .map { isNeedShowGeolocationAlert(!it) }
```
I'm using RxJava  '2.0.5' and RxLocation '1.0.3'. Play Services Version is '10.2.1'

What might be wrong?

**Comment by vdubedout** [comment]
UndeliverableException is thrown by RX when you disposed a subscriptions and an Error happens after that. It can't use the subscribe-onError because it's already unsubscribed. I don't think this error will even pass into your onErrorReturn.

**Comment by patloew** [comment]
You can set a default error handler for these cases.
