### ISSUE TITLE
java.io.IOException: Service not Available

### ISSUE THREAD

**Issue by iballan** [patloew/RxLocation#59]
The stacktrace:

```
java.io.IOException: Service not Available
     at android.location.Geocoder.getFromLocation(Geocoder.java:136)
     at com.patloew.rxlocation.Geocoding.lambda$fromLocation$1$Geocoding(Geocoding.java:62)
     at com.patloew.rxlocation.Geocoding$$Lambda$0.call(Unknown Source)
     at (SingleFromCallable.java:45)
     at io.reactivex.Single.subscribe(Single.java:2801)
     at (SingleFlatMapMaybe.java:41)
     at io.reactivex.Maybe.subscribe(Maybe.java:3749)
     at aybeToObservable.java:43)
     at io.reactivex.Observable.subscribe(Observable.java:10981)
     at r.subscribeInner(ObservableFlatMap.java:162)
     at r.onNext(ObservableFlatMap.java:139)
     at bserver.drainNormal(ObservableObserveOn.java:200)
     at bserver.run(ObservableObserveOn.java:252)
     at ndlerScheduler.java:109)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5910)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

Android versions that i have tested on: 5.1 and 6
Locales : Arabic and English

**Comment by patloew** [comment]
As you can see in the stack trace, this problem actually occurs in an Android framework class.

````
java.io.IOException: Service not Available
     at android.location.Geocoder.getFromLocation(Geocoder.java:136)
````

There's nothing the library can do about it, but I found [this issue on the Android issue tracker](https://issuetracker.google.com/issues/36956130), maybe this can help your case?

**Comment by amiyo-biswas** [comment]
Facing same problem
