### ISSUE TITLE
Unexpected GoogleApiConnectionException

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [patloew/RxLocation#60]
I'm getting `GoogleApiConnectionException` on some devices when trying to fetch the last known location. None of my test devices experience the issue but some users do. Below is the error that's emitted to the observer:
```
com.patloew.rxlocation.GoogleApiConnectionException: Error connecting to GoogleApiClient.
                        at com.patloew.rxlocation.RxLocationMaybeOnSubscribe$ApiClientConnectionCallbacks.onConnectionFailed(RxLocationMaybeOnSubscribe.java:92)
                        at com.google.android.gms.common.internal.zzae.zzk(Unknown Source)
                        at com.google.android.gms.common.api.internal.zzba.zzc(Unknown Source)
                        at com.google.android.gms.common.api.internal.zzao.zze(Unknown Source)
                        at com.google.android.gms.common.api.internal.zzao.zza(Unknown Source)
                        at com.google.android.gms.common.api.internal.zzas.zzaib(Unknown Source)
                        at com.google.android.gms.common.api.internal.zzbj.zzc(Unknown Source)
                        at com.google.android.gms.common.api.internal.zzbk.handleMessage(Unknown Source)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:154)
                        at android.app.ActivityThread.main(ActivityThread.java:6688)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

I'm at a loss as to what to do. Right now I can only guess. Stepping through the code it looks like it tries to connect to the API with `LocationServices` and `ActivityRecognition`. Is it possible that some devices don't support the Activity Recognition API?

**Comment by apm29** [comment]
Same problem

**Comment by patloew** [comment]
This library is now deprecated and not maintained anymore. Please switch to the [CoLocation library](https://github.com/patloew/CoLocation).
